# Generated by Django 3.2.6 on 2021-12-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Категория'),
        ),
    ]
