# Generated by Django 3.2.6 on 2021-12-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(null=True, upload_to='cat_photos', verbose_name='Картинка категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание категории'),
        ),
    ]
