# Generated by Django 3.2.6 on 2022-01-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220106_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пользователь'),
        ),
    ]
