# Generated by Django 3.2.6 on 2022-01-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220107_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/PrymaryPhoto', verbose_name='Фото'),
        ),
    ]
