# Generated by Django 3.2.6 on 2022-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_primary_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propvalue',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
    ]
