# Generated by Django 3.2.6 on 2022-01-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_productphoto_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propvalue',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар'),
        ),
    ]
