# Generated by Django 3.2.6 on 2022-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=30, verbose_name='Цена'),
        ),
    ]
