# Generated by Django 3.2.6 on 2022-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20220110_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оценка'),
        ),
    ]
