# Generated by Django 3.2.6 on 2022-01-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20220112_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Доступное количество'),
        ),
    ]
