# Generated by Django 3.2.6 on 2022-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20220112_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='оплата'),
        ),
        migrations.AddField(
            model_name='order',
            name='planet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Планета (для доставки)'),
        ),
    ]
