# Generated by Django 3.2.6 on 2022-01-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20220114_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Заказ закрыт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Требуется доставка'),
        ),
    ]
