# Generated by Django 3.2.6 on 2022-01-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0022_order_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='photos/users', verbose_name='Фото пользователя')),
            ],
        ),
    ]
